import { WorkProps } from "@/components/WorkCard";

export const DoneWorks: WorkProps[] = [
  {
    id: 1,
    image: "/project_images/10k-promoter.png",
    name: "10k.uz | Promoter",
    project_link: "https://promoter.10k.uz",
    stacks: [
      "React.js",
      "TailwindCSS",
      "Typescript",
      "Node.js",
      "Nest.js",
      "PostgreSQL",
    ],
  },
  {
    id: 2,
    image: "/project_images/10k-admin.png",
    name: "10k.uz | Admin",
    project_link: "https://admin.10k.uz",
    stacks: [
      "React.js",
      "Ant Design",
      "ShadCn Ui",
      "TailwindCSS",
      "Typescript",
      "Node.js",
      "Nest.js",
      "PostgreSQL",
    ],
  },
  {
    id: 3,
    image: "/project_images/urganchttb.jpg",
    name: "UrganchTTB.uz",
    project_link: "https://urganchttb.uz",
    stacks: [
      "React.js",
      "Javascript",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "PostgreSQL",
    ],
  },
  {
    id: 4,
    image: "/project_images/x-clone.webp",
    name: "X-Clone (Y)",
    project_link: "https://y-twitter.vercel.app/",
    stacks: [
      "Next.js",
      "Typescript",
      "TailwindCSS",
      "NextAuth",
      "ShadCn UI",
      "Node.js",
      "MongoDB",
      "Mongoose",
    ],
  },
  {
    id: 5,
    image: "/project_images/x-clone.webp",
    name: "Loadmore.uz",
    project_link: "https://y-twitter.vercel.app/",
    stacks: [
      "Next.js",
      "Typescript",
      "TailwindCSS",
      "NextAuth",
      "ShadCn UI",
      "Node.js",
      "MongoDB",
      "Mongoose",
    ],
  },
];
